-- MySQL Script generated by MySQL Workbench
-- Sun Aug 20 18:14:56 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gestacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestacao` DEFAULT CHARACTER SET utf8 ;
USE `gestacao` ;

-- -----------------------------------------------------
-- Create user
-- -----------------------------------------------------
CREATE USER `sisgestacao`@`localhost` identified by "123456";
GRANT ALL PRIVILEGES ON gestacao.* TO `sisgestacao`@`localhost`;
FLUSH PRIVILEGES;

-- -----------------------------------------------------
-- Table `gestacao`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestacao`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `idade` INT NOT NULL,
  `dataGestacao` DATE NOT NULL,
  `peso` FLOAT NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestacao`.`bebes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestacao`.`bebes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `sexo` VARCHAR(12) NULL DEFAULT NULL,
  `nascimento` DATE NULL DEFAULT NULL,
  `users_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_bebes_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_bebes_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `gestacao`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestacao`.`consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestacao`.`consultas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `horario` VARCHAR(50) NOT NULL,
  `medico` VARCHAR(50) NOT NULL,
  `local` VARCHAR(100) NOT NULL,
  `pesomae` FLOAT NOT NULL,
  `pesobebe` FLOAT NOT NULL,
  `resumo` VARCHAR(200) NOT NULL,
  `users_id` INT UNSIGNED NOT NULL,
  `bebes_id` INT UNSIGNED NOT NULL,
  `bebes_users_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `bebes_id`, `bebes_users_id`),
  INDEX `fk_consultas_users1_idx` (`users_id` ASC),
  INDEX `fk_consultas_bebes1_idx` (`bebes_id` ASC, `bebes_users_id` ASC),
  CONSTRAINT `fk_consultas_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `gestacao`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consultas_bebes1`
    FOREIGN KEY (`bebes_id` , `bebes_users_id`)
    REFERENCES `gestacao`.`bebes` (`id` , `users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
